# Deploy docker image into AWS ECS

- name: build docker image
  hosts: localhost
  roles:
   - build_image

- name: create ecs_ecr and push image
  hosts: localhost
  roles:
   - ecr_push 

- name: create vpc
  hosts: localhost
  roles:
   - vpc_create

- name: create ecs cluster
  hosts: localhost
  roles:
   - ecs_cluster
